return {
  -- Catppuccin theme configuration
  {
    "catppuccin/nvim",
    name = "catppuccin", 
    priority = 1000,
    opts = {
      flavour = "macchiato",
      background = {
        light = "latte",
        dark = "macchiato",
      },
      transparent_background = false,
      show_end_of_buffer = false,
      term_colors = true,
      no_italic = false,
      no_bold = false,
      no_underline = false,
      styles = {
        comments = { "italic" },
        conditionals = { "italic" },
      },
      integrations = {
        cmp = true,
        gitsigns = true,
        nvimtree = true,
        treesitter = true,
        telescope = true,
        which_key = true,
        mason = true,
        noice = true,
        illuminate = true,
        markdown = true,
        neotest = true,
        lsp_trouble = true,
        native_lsp = {
          enabled = true,
          virtual_text = {
            errors = { "italic" },
            hints = { "italic" },
            warnings = { "italic" },
            information = { "italic" },
          },
          underlines = {
            errors = { "underline" },
            hints = { "underline" },
            warnings = { "underline" },
            information = { "underline" },
          },
        },
      },
    },
  },
  
  -- Web devicons with Catppuccin colors
  {
    "nvim-tree/nvim-web-devicons",
    opts = {
      color_icons = true,
      default = true,
      strict = true,
      override_by_filename = {
        [".gitignore"] = { icon = "", color = "#6e738d", name = "Gitignore" },
        [".env"] = { icon = "", color = "#eed49f", name = "Env" },
        ["package.json"] = { icon = "", color = "#a6da95", name = "PackageJson" },
        ["README.md"] = { icon = "", color = "#8aadf4", name = "Readme" },
        ["dockerfile"] = { icon = "", color = "#8aadf4", name = "Dockerfile" },
        ["Dockerfile"] = { icon = "", color = "#8aadf4", name = "Dockerfile" },
        ["tsconfig.json"] = { icon = "", color = "#8aadf4", name = "TypeScriptConfig" },
        ["tailwind.config.js"] = { icon = "󱏿", color = "#8bd5ca", name = "TailwindConfig" },
        ["next.config.js"] = { icon = "", color = "#cad3f5", name = "NextConfig" },
        ["vite.config.js"] = { icon = "", color = "#eed49f", name = "ViteConfig" },
        ["biome.json"] = { icon = "", color = "#eed49f", name = "BiomeConfig" },
        ["biome.jsonc"] = { icon = "", color = "#eed49f", name = "BiomeConfig" },
      },
      override_by_extension = {
        ["js"] = { icon = "", color = "#eed49f", name = "JavaScript" },
        ["jsx"] = { icon = "", color = "#8bd5ca", name = "JSX" },
        ["ts"] = { icon = "", color = "#8aadf4", name = "TypeScript" },
        ["tsx"] = { icon = "", color = "#8bd5ca", name = "TSX" },
        ["vue"] = { icon = "", color = "#a6da95", name = "Vue" },
        ["svelte"] = { icon = "", color = "#f5a97f", name = "Svelte" },
        ["html"] = { icon = "", color = "#f5a97f", name = "HTML" },
        ["css"] = { icon = "", color = "#8aadf4", name = "CSS" },
        ["scss"] = { icon = "", color = "#f5bde6", name = "SCSS" },
        ["json"] = { icon = "", color = "#eed49f", name = "JSON" },
        ["md"] = { icon = "", color = "#8aadf4", name = "Markdown" },
        ["py"] = { icon = "", color = "#8aadf4", name = "Python" },
        ["rs"] = { icon = "", color = "#f5a97f", name = "Rust" },
        ["go"] = { icon = "", color = "#8bd5ca", name = "Go" },
        ["lua"] = { icon = "", color = "#8aadf4", name = "Lua" },
        ["vim"] = { icon = "", color = "#a6da95", name = "Vim" },
      },
    },
  },
}
